<?php
/**
 * Install all sidebars
 *
 * @package photolab
 */

$config_sidebars = array(
	array(
		'name'          => __( 'Front page full width widget area', 'blogetti' ),
		'id'            => 'full-width',
		'description'   => __( 'After header', 'blogetti' ),
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Before content widget area', 'blogetti' ),
		'id'            => 'main',
		'description'   => __( 'After full width sidebar', 'blogetti' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Before loop widget area', 'blogetti' ),
		'id'            => 'before-loop-widget-area',
		'description'   => __( 'After full width sidebar', 'blogetti' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Content widget area', 'blogetti' ),
		'id'            => 'content-sidebar-0',
		'description'   => __( 'After posts sidebar', 'blogetti' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Front page after content widget area', 'blogetti' ),
		'id'            => 'content-sidebar',
		'description'   => __( 'After posts sidebar', 'blogetti' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Front page after content full width widget area', 'blogetti' ),
		'id'            => 'after-content-full-width-widget-area',
		'description'   => __( 'After content full width widget area', 'blogetti' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Left sidebar', 'blogetti' ),
		'id'            => 'left-sidebar',
		'description'   => __( 'Allowed only on static pages', 'blogetti' ),
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Right sidebar', 'blogetti' ),
		'id'            => 'right-sidebar',
		'description'   => __( 'Allowed only on static pages', 'blogetti' ),
		'before_widget' => '<div id="%1$s" class="widget %2$s">',
		'after_widget'  => '</div>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Footer Widget Area', 'blogetti' ),
		'id'            => 'footer',
		'description'   => '',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Footer First Column', 'blogetti' ),
		'id'            => 'footer-1',
		'description'   => '',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Footer Second Column', 'blogetti' ),
		'id'            => 'footer-2',
		'description'   => '',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Footer Third Column', 'blogetti' ),
		'id'            => 'footer-3',
		'description'   => '',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
	array(
		'name'          => __( 'Footer Fourth Column', 'blogetti' ),
		'id'            => 'footer-4',
		'description'   => '',
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget'  => '</aside>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>',
	),
);
return Utils::array_push_values( $config_sidebars, Model_Sidebar_Settings::get_sidebars_options() );
